### ISSUE TITLE
Setlistbot down?

### ISSUE THREAD

**Issue by cameronurnes** [cjbanna/setlistbot#25]
Looks like /u/setlistbot hasn't been working since May 1st on any subreddit.  Thanks for your work!

**Comment by cjbanna** [comment]
Thanks for letting me know! Looks like Reddit blocked the bot on May 1. It's not clear why. I am investigating.

**Comment by cjbanna** [comment]
I have a ticket out to Reddit to figure out why the bot was blocked.

No changes were pushed recently and there were no error responses from Reddit before the block. The block message started at 2023-05-01T17:52:00 UTC. 

30 seconds prior, the bot successfully checked for new comments/posts at 2023-05-01T17:51:30 UTC

1 minute prior, it was able to reply to [a comment](https://old.reddit.com/r/gratefuldead/comments/134rjhf/best_dead_set_ever_32881_first_set_imo/jigi6gg/) at 2023-05-01T17:51:00 UTC

¯\\\_(ツ)_/¯
